
server:
  port: 9091
  servlet:
    session:
      cookie:
       name: UISESSION
        
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          custom-client:
            client-id: clientapp2
            client-secret: vanna
            client-name: Auth Server
            scope: read
            provider: custom-provider
            redirect-uri: http://localhost:9091/login/oauth2/code/
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: http://localhost:8080/oauth/token
            authorization-uri: http://localhost:8080/oauth/authorize
            user-info-uri: http://localhost:8080/api/data
            user-name-attribute: ename